name: Metrics
on:
  schedule: [{cron: "0 * * * *"}]
  push: {branches: ["master", "main"]}
  workflow_dispatch:
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}

          user: SuperSandro2000
          template: classic
          base: header, activity, community, repositories, metadata
          config_animations: yes
          config_timezone: Europe/Berlin
          optimize: no
          repositories_forks: yes
          use_prebuilt_image: yes

          plugin_achievements: yes
          plugin_achievements_ignored: explorer, infographile, member, worker, verified
          plugin_achievements_secrets: yes
          plugin_achievements_threshold: A
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          #plugin_languages: yes
          #plugin_languages_details: bytes-size, percentage
          #plugin_languages_skipped: GOD-GOG
          plugin_lines: yes
          #plugin_notable: yes
          #plugin_notable_filter: stars:>100
          #plugin_notable_repositories: yes
          #plugin_topics: yes
          #plugin_topics_mode: mastered
          #plugin_topics_limit: 20
